# CIRCUITPY_WIFI_SSID = "praxis3iot" # the WiFi network to connect to
# CIRCUITPY_WIFI_PASSWORD = "ESC204MY150" # the WiFi password

CIRCUITPY_WIFI_SSID = "network-name" # the WiFi network to connect to
CIRCUITPY_WIFI_PASSWORD = "network-password" # the WiFi password

# see here on how to access your username and key: https://io.adafruit.com/api/docs/#adafruit-io-http-api
aio_username = "aio-username" # replace text with your aio username
aio_key = "aio-key" # replace text with your aio key.

# Create an account on a MQTT broker (e.g. HiveMQ Cloud) and enter your clusters's own username and password
MQTT_USERNAME = "mqtt-username" 
MQTT_PASSWORD = "mqtt-password"

SERVER_IP = "172.29.225.14"
ANEMOMETER_IP = "172.29.225.18"
